# Default values for feingkai-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 770927716090.dkr.ecr.us-east-1.amazonaws.com/bluelightltd/feingkai-frontend
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  externalPort: 443


domainName: dev.feingkai.com
ingressClass: nginx
#certIssuer: letsencrypt-staging
certIssuer: letsencrypt-prod
#certSecret: example-nodejs-crt  # for staging
certSecret: feingkai-prod-crt

# /etc/nginx/nginx.conf   /etc/nginx/conf.d
# /usr/share/nginx/html
# Set custom nginx config file
appConfigFile: "default.conf"

ingress:
  enabled: true
  annotations: # {}
  staticIpName: feingkai-frontend

#     kubernetes.io/ingress.class: nginx
# #    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - dev.feingkai.com
#    - dev.feingkai.com
#    - barong-dev.feingkai.com
#    - phpadmin-dev.feingkai.com
#    - auth.feingkai.com
  # tls: []
  # #  - secretName: chart-example-tls
  # #    hosts:
  # #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
